// This file will be auto-generated by Supabase CLI once connected.
// For now, manual types matching our schema.

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          settings: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["organizations"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["organizations"]["Insert"]>;
      };
      brands: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          color_primary: string;
          color_secondary: string;
          domain: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["brands"]["Row"], "id" | "created_at" | "updated_at" | "is_active">;
        Update: Partial<Database["public"]["Tables"]["brands"]["Insert"]>;
      };
      profiles: {
        Row: {
          id: string;
          org_id: string | null;
          full_name: string;
          phone: string | null;
          email: string | null;
          avatar_url: string | null;
          role: "super_admin" | "org_admin" | "kitchen_manager" | "production_staff" | "delivery_manager" | "customer";
          city_id: string | null;
          kitchen_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at" | "is_active">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      menu_items: {
        Row: {
          id: string;
          brand_id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          short_desc: string | null;
          image_url: string | null;
          base_price: number;
          calories: number | null;
          protein_g: number | null;
          fiber_g: number | null;
          tags: string[];
          is_customizable: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["menu_items"]["Row"], "id" | "created_at" | "updated_at" | "is_active" | "is_customizable" | "sort_order" | "tags">;
        Update: Partial<Database["public"]["Tables"]["menu_items"]["Insert"]>;
      };
      menu_categories: {
        Row: {
          id: string;
          brand_id: string;
          name: string;
          slug: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["menu_categories"]["Row"], "id" | "sort_order" | "is_active">;
        Update: Partial<Database["public"]["Tables"]["menu_categories"]["Insert"]>;
      };
      plans: {
        Row: {
          id: string;
          brand_id: string;
          name: string;
          slug: string;
          duration_days: number;
          meals_per_day: number;
          price_per_meal: number;
          total_price: number;
          discount_pct: number;
          description: string | null;
          features: string[];
          is_trial: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["plans"]["Row"], "id" | "created_at" | "is_active" | "is_trial" | "sort_order" | "meals_per_day" | "discount_pct">;
        Update: Partial<Database["public"]["Tables"]["plans"]["Insert"]>;
      };
      subscriptions: {
        Row: {
          id: string;
          subscription_no: string;
          profile_id: string;
          plan_id: string;
          brand_id: string;
          kitchen_id: string;
          address_id: string;
          status: "pending_payment" | "active" | "paused" | "completed" | "cancelled" | "expired";
          start_date: string;
          end_date: string;
          total_meals: number;
          meals_delivered: number;
          meals_remaining: number;
          pause_dates: string[];
          skip_dates: string[];
          preferences: Record<string, unknown>;
          amount_paid: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["subscriptions"]["Row"], "id" | "created_at" | "updated_at" | "meals_delivered" | "pause_dates" | "skip_dates">;
        Update: Partial<Database["public"]["Tables"]["subscriptions"]["Insert"]>;
      };
      orders: {
        Row: {
          id: string;
          order_no: string;
          subscription_id: string;
          profile_id: string;
          kitchen_id: string;
          address_id: string;
          delivery_date: string;
          menu_item_id: string;
          quantity: number;
          status: "scheduled" | "locked" | "in_production" | "packed" | "dispatched" | "delivered" | "skipped" | "paused" | "cancelled";
          locked_at: string | null;
          customizations: Record<string, unknown>;
          delivery_slot: string | null;
          driver_id: string | null;
          delivered_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["orders"]["Row"], "id" | "created_at" | "updated_at" | "locked_at" | "quantity">;
        Update: Partial<Database["public"]["Tables"]["orders"]["Insert"]>;
      };
      daily_snapshots: {
        Row: {
          id: string;
          kitchen_id: string;
          production_date: string;
          snapshot_taken: string;
          status: "pending" | "processing" | "completed" | "failed";
          total_orders: number;
          locked_orders: number;
          skipped_orders: number;
          summary: Record<string, unknown>;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["daily_snapshots"]["Row"], "id" | "created_at" | "total_orders" | "locked_orders" | "skipped_orders">;
        Update: Partial<Database["public"]["Tables"]["daily_snapshots"]["Insert"]>;
      };
      ingredients: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          sku: string | null;
          unit: string;
          category: string | null;
          shelf_life_days: number | null;
          storage_type: "ambient" | "refrigerated" | "frozen";
          cost_per_unit: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["ingredients"]["Row"], "id" | "created_at" | "is_active">;
        Update: Partial<Database["public"]["Tables"]["ingredients"]["Insert"]>;
      };
      inventory: {
        Row: {
          id: string;
          kitchen_id: string;
          ingredient_id: string;
          current_qty: number;
          unit: string;
          reorder_level: number;
          last_restocked: string | null;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["inventory"]["Row"], "id" | "updated_at" | "reorder_level">;
        Update: Partial<Database["public"]["Tables"]["inventory"]["Insert"]>;
      };
      inventory_transactions: {
        Row: {
          id: string;
          kitchen_id: string;
          ingredient_id: string;
          tx_type: "purchase" | "production_use" | "adjustment" | "waste" | "return";
          quantity: number;
          reference_id: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["inventory_transactions"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["inventory_transactions"]["Insert"]>;
      };
      production_requirements: {
        Row: {
          id: string;
          snapshot_id: string;
          menu_item_id: string;
          quantity: number;
          status: "pending" | "in_progress" | "completed";
        };
        Insert: Omit<Database["public"]["Tables"]["production_requirements"]["Row"], "id">;
        Update: Partial<Database["public"]["Tables"]["production_requirements"]["Insert"]>;
      };
      ingredient_requirements: {
        Row: {
          id: string;
          snapshot_id: string;
          ingredient_id: string;
          required_qty: number;
          available_qty: number;
          shortage_qty: number;
          unit: string;
        };
        Insert: Omit<Database["public"]["Tables"]["ingredient_requirements"]["Row"], "id" | "available_qty" | "shortage_qty">;
        Update: Partial<Database["public"]["Tables"]["ingredient_requirements"]["Insert"]>;
      };
      addresses: {
        Row: {
          id: string;
          profile_id: string;
          label: string;
          line1: string;
          line2: string | null;
          city: string;
          state: string;
          pincode: string;
          lat: number | null;
          lng: number | null;
          zone_id: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["addresses"]["Row"], "id" | "created_at" | "is_default">;
        Update: Partial<Database["public"]["Tables"]["addresses"]["Insert"]>;
      };
      payments: {
        Row: {
          id: string;
          subscription_id: string;
          profile_id: string;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          amount: number;
          currency: string;
          status: "created" | "authorized" | "captured" | "failed" | "refunded";
          method: string | null;
          error_code: string | null;
          error_desc: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["payments"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["payments"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      order_status: "scheduled" | "locked" | "in_production" | "packed" | "dispatched" | "delivered" | "skipped" | "paused" | "cancelled";
      subscription_status: "pending_payment" | "active" | "paused" | "completed" | "cancelled" | "expired";
      payment_status: "created" | "authorized" | "captured" | "failed" | "refunded";
      snapshot_status: "pending" | "processing" | "completed" | "failed";
      inventory_tx_type: "purchase" | "production_use" | "adjustment" | "waste" | "return";
    };
  };
};
